### ISSUE TITLE
SSC Assistant - add to disclaimer that it is in pilot mode

### ISSUE THREAD

**Issue by GuillaumeTurcotte** [dto-btn/ssc-assistant#62]

**Comment by davidsimard2** [comment]
- [ ] Create disclaimer draft message
- [ ] Submit to Comms for review
- [ ] Final review

**Comment by GuillaumeTurcotte** [comment]
> DISCLAIMER
The SSC Assistant is in pilot phase and uses Azure OpenAI. Answers may be incorrect even if they seem reliable. Just like humans, AI can make mistakes. Your feedback is important to help us improve the tool.
> DO NOT SEND ANY PROTECTED INFORMATION IN THE CHATBOT.

> AVIS
> L’assistant SPC est en phase pilote et utilise l’IA d’Azure OpenAI. Les réponses peuvent être incorrectes même si elles semblent fiables. Tout comme les humains, l’IA peut commettre des erreurs. Votre avis est important pour nous aider à améliorer l’outil.
> N'ENVOYEZ PAS D'INFORMATIONS CONFIDENTIELLES DANS LE CHATBOT.
